from __future__ import annotations

import json
import os
from typing import Any, Dict, List, Optional, Sequence, TypedDict

from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, ToolMessage
from langchain_core.tools import BaseTool, StructuredTool, tool
from langgraph.graph import END, StateGraph
from langgraph.prebuilt import create_react_agent

from qos_system_lg.a2a_client import send_text_message
from qos_system_lg.app_config import get_str
from qos_system_lg.llm_client import build_chat_llm, llm_label, try_parse_json_object


class GraphState(TypedDict, total=False):
    """
    LangGraph shared state (kept JSON-serializable as much as possible).

    Key fields output at each step in `/run_demo_stream`:
    - alarm: alarm object (generated by the LLM after querying Neo4j)
    - flow: Flow + SLA (generated by the LLM after querying Neo4j)
    - analysis: pressure analysis and path selection (LLM + Neo4j)
    - plan: remediation plan (LLM)
    - execution: executor result (LLM after calling A2A)
    - verification: regression verification result (LLM + Neo4j)
    """

    scenario: str
    flow_id: str

    alarm: Dict[str, Any]
    flow: Dict[str, Any]
    analysis: Dict[str, Any]
    plan: Dict[str, Any]
    execution: Dict[str, Any]
    verification: Dict[str, Any]

    should_remediate: bool

    # MCP tool call audit
    mcp_audit: List[Dict[str, Any]]

    # Notification results
    notifications: List[Dict[str, Any]]

    error: str
    step: str


def _tool_text(result: Any) -> str:
    """
    Normalize tool return values into text (for logging/auditing).

    """

    if result is None:
        return ""
    if isinstance(result, bytes):
        try:
            return result.decode("utf-8")
        except Exception:
            return result.decode(errors="ignore")
    if isinstance(result, str):
        return result
    if isinstance(result, tuple) and len(result) == 2:
        return _tool_text(result[0])
    if isinstance(result, list):
        if all(isinstance(x, str) for x in result):
            return "\n".join([x for x in result if x])
        if all(isinstance(x, dict) for x in result):
            texts: list[str] = []
            for item in result:
                if "text" in item and isinstance(item.get("text"), str):
                    texts.append(item["text"])
                elif "content" in item:
                    texts.append(_tool_text(item["content"]))
            joined = "\n".join([t for t in texts if t])
            return joined if joined else str(result)
        return str(result)
    if hasattr(result, "content"):
        try:
            return _tool_text(getattr(result, "content"))
        except Exception:
            pass
    if isinstance(result, dict):
        if "text" in result and isinstance(result.get("text"), str):
            return result["text"]
        if "content" in result:
            return _tool_text(result["content"])
    return str(result)


def _extract_llm_json(messages: Sequence[BaseMessage]) -> tuple[Optional[Dict[str, Any]], str]:
    """
    Traverse messages in reverse order, find the last AIMessage,
    and try to parse it into a JSON object.

    """

    for m in reversed(messages):
        if not isinstance(m, AIMessage):
            continue
        text = m.content if isinstance(m.content, str) else str(m.content)
        obj = try_parse_json_object(text)
        if obj is not None:
            return obj, text

    for m in reversed(messages):
        if isinstance(m, AIMessage):
            text = m.content if isinstance(m.content, str) else str(m.content)
            return None, text
    return None, ""


def _extract_tool_audit(messages: Sequence[BaseMessage]) -> List[Dict[str, Any]]:
    """
    Extract tool_calls and tool results from the agent loop
    into serializable audit data.
    """

    results_by_id: dict[str, str] = {}
    for m in messages:
        if isinstance(m, ToolMessage):
            results_by_id[m.tool_call_id] = _tool_text(m.content)

    audit: List[Dict[str, Any]] = []
    for m in messages:
        if not isinstance(m, AIMessage):
            continue
        for tc in m.tool_calls or []:
            call_id = tc.get("id")
            name = tc.get("name")
            args = tc.get("args")
            entry: Dict[str, Any] = {"name": name, "args": args}
            if isinstance(call_id, str):
                entry["id"] = call_id
                if call_id in results_by_id:
                    entry["result"] = results_by_id[call_id]
            audit.append(entry)
    return audit


def _merge_notifications(state: GraphState, audit: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    notifications = list(state.get("notifications") or [])
    for a in audit:
        if a.get("name") != "send_email":
            continue
        args = a.get("args") or {}
        result = a.get("result")
        ok = True
        if isinstance(result, str):
            if (
                "error occurred" in result.lower()
                or "authentication failed" in result.lower()
                or "error" in result.lower()
            ):
                ok = False
        notifications.append(
            {
                "type": "email",
                "to": (args.get("to_addr") if isinstance(args, dict) else None),
                "subject": (args.get("subject") if isinstance(args, dict) else None),
                "ok": ok,
                "result": result,
                **({} if ok else {"error": result}),
            }
        )
    return notifications


def _get_prompt_or_error(prompt_key: str) -> str:
    prompt = get_str("prompts", prompt_key, fallback="")
    if not prompt:
        raise ValueError(f"config.ini is missing prompts.{prompt_key}")
    return prompt


def build_workflow(
    *,
    tools: Sequence[BaseTool],
    executor_a2a_url: str,
    read_tool_name: str = "read_neo4j_cypher",
    write_tool_name: str = "write_neo4j_cypher",
    email_tool_name: str = "send_email",
) -> Any:
    """
    Build the LangGraph workflow (strict order with early stopping).

    Important notes (as requested):
    - Each node in this workflow is an “LLM Agent” (with tools).
    - Neo4j / Email and other MCP tools are automatically selected and invoked by the LLM
      (langchain-mcp-adapters).
    - The code is only responsible for: defining node boundaries, passing state to the LLM,
      and merging the LLM’s JSON output back into the state.
    """

    # Workflow mode:
    # - deterministic: do NOT require an external LLM; run fully deterministic multi-path logic.
    # - llm: keep the original "LLM agent + tool calling" demo workflow.

    mode = (os.getenv("QOS_WORKFLOW_MODE") or "deterministic").strip().lower()
    if mode in {"deterministic", "det", "mp"}:
        from qos_system_lg.deterministic_workflow import build_deterministic_workflow

        return build_deterministic_workflow(
            tools=tools,
            executor_a2a_url=executor_a2a_url,
            read_tool_name=read_tool_name,
            write_tool_name=write_tool_name,
            email_tool_name=email_tool_name,
        )

    llm = build_chat_llm(temperature=0.2, streaming=False)
    if not llm:
        raise RuntimeError(
            "Real LLM not configured: please set GEMINI_API_KEY/GEMINI_MODEL (or GOOGLE_API_KEY/GOOGLE_MODEL) "
            "or OPENAI_API_KEY/OPENAI_BASE_URL/OPENAI_MODEL in qos-system-lg/.env"
        )

    _NODE_JSON_SKELETON: dict[str, Dict[str, Any]] = {
        "AlarmIngest": {"step": "AlarmIngest", "alarm": {}, "should_remediate": False},
        "ConfirmAlarm": {
            "step": "ConfirmAlarm",
            "flow": {},
            "verification": {
                "status": "OK|VIOLATED",
                "bw_ok": True,
                "latency_ok": True,
                "rate": 0.0,
                "latency": 0.0,
                "reason": "...",
            },
            "should_remediate": False,
        },
        "AnalyzePressure": {"step": "AnalyzePressure", "analysis": {}, "should_remediate": True},
        "PlanChange": {"step": "PlanChange", "plan": {}},
        "ExecuteChange": {"step": "ExecuteChange", "execution": {"status": "Success|Failure|Rollback", "log": "..."}},
        "RegressionVerify": {
            "step": "RegressionVerify",
            "verification": {
                "status": "OK|VIOLATED",
                "bw_ok": True,
                "latency_ok": True,
                "rate": 0.0,
                "latency": 0.0,
                "reason": "...",
            },
        },
    }

    async def _repair_output_to_json(*, node_name: str, prompt_key: str, bad_text: str) -> Optional[Dict[str, Any]]:
        """
        When the LLM does not output parsable JSON, perform a “JSON repair” call
        (no tools, only format correction).

        """

        from langchain_core.messages import HumanMessage as _HumanMessage
        from langchain_core.messages import SystemMessage as _SystemMessage

        skeleton = _NODE_JSON_SKELETON.get(node_name) or {"step": node_name}
        repair_input = {
            "node": node_name,
            "prompt_key": prompt_key,
            "expected_json_skeleton": skeleton,
            "bad_output": bad_text,
            "rules": [
                "Output exactly one JSON object (no Markdown, no explanation, no code fence).",
                "Do not use JS expressions (e.g., new Date(), regex, string concatenation); all values must be JSON literals.",
                "The step field must be present and equal to node.",
            ],
        }
        repair_input_text = json.dumps(repair_input, ensure_ascii=False, indent=2, default=str)
        print(f"[LLM][{node_name}][JSON_REPAIR] {llm_label()} INPUT:\n{repair_input_text}", flush=True)

        resp = await llm.ainvoke(
            [
                _SystemMessage(
                    content=(
                        "You are a JSON repairer. Your task is to fix the provided bad_output "
                        "into a strict JSON object. Output JSON only.\n"
                    )
                ),
                _HumanMessage(content=repair_input_text),
            ]
        )
        text = resp.content if hasattr(resp, "content") else str(resp)
        text = text if isinstance(text, str) else str(text)
        print(f"[LLM][{node_name}][JSON_REPAIR] {llm_label()} OUTPUT:\n{text}", flush=True)
        return try_parse_json_object(text)

    @tool
    async def a2a_send_executor_message(text: str, context_id: Optional[str] = None) -> str:
        """
        Send a text message to the executor via the A2A protocol
        and return its text response.

        """

        resp = await send_text_message(
            agent_card_url_or_base=executor_a2a_url,
            text=text,
            context_id=context_id,
            timeout_s=30.0,
        )
        return resp.text

    def _stringify_tool_output(value: Any) -> str:

        if value is None:
            return ""
        if isinstance(value, str):
            return value
        if isinstance(value, bytes):
            try:
                return value.decode("utf-8")
            except Exception:
                return value.decode(errors="ignore")
        try:
            return json.dumps(value, ensure_ascii=False, default=str)
        except Exception:
            return str(value)

    def _wrap_tool_return_str(t: BaseTool) -> BaseTool:
        """
        Wrap a tool to keep name/args_schema unchanged,
        but ensure the return value is a string to avoid LLM provider 400 errors.

        """

        async def _call(**kwargs: Any) -> str:
            try:
                out = await t.ainvoke(kwargs)
                return _stringify_tool_output(out)
            except Exception as e:
                # Do not crash the whole Agent on tool failure;
                # return the error as a string so the LLM can continue reasoning.
                return f"[TOOL_ERROR][{t.name}] {e}"

        args_schema = getattr(t, "args_schema", None)

        return StructuredTool.from_function(
            func=None,
            coroutine=_call,
            name=t.name,
            description=getattr(t, "description", None) or "",
            args_schema=args_schema,
            infer_schema=(args_schema is None),
            response_format="content",
        )

    safe_mcp_tools = [_wrap_tool_return_str(t) for t in tools]
    tool_list = safe_mcp_tools + [a2a_send_executor_message]

    def _pick(*names: str) -> List[BaseTool]:
        wanted = set(names)
        return [t for t in tool_list if t.name in wanted]

    async def _run_agent_node(
        *,
        node_name: str,
        prompt_key: str,
        state: GraphState,
        node_tools: Sequence[BaseTool],
    ) -> GraphState:
        """
        Generic node executor:
        - Read the prompt from config.ini
        - Run the ReAct agent (tools auto-invoked by the LLM)
        - Parse the final JSON and merge it back into state
        - Extract tool audit / notifications (for step-by-step logging)

        """

        scenario = state.get("scenario") or "QOS_DEMO"
        flow_id = state.get("flow_id") or "FLOW-001"

        prompt = _get_prompt_or_error(prompt_key)
        prompt = (
            prompt.replace("read_neo4j_cypher", read_tool_name)
            .replace("write_neo4j_cypher", write_tool_name)
            .replace("send_email", email_tool_name)
        )
        agent = create_react_agent(llm, node_tools, prompt=prompt, version="v2")

        input_obj = {
            "node": node_name,
            "scenario": scenario,
            "flow_id": flow_id,
            "state": state,
            "config": {
                "alerting": {
                    "email_to": get_str("alerting", "email_to", fallback=""),
                    "email_cc": get_str("alerting", "email_cc", fallback=""),
                    "email_subject": get_str("alerting", "email_subject", fallback=""),
                    "email_body": get_str("alerting", "email_body", fallback=""),
                }
            },
        }

        input_text = json.dumps(input_obj, ensure_ascii=False, indent=2, default=str)
        tool_names = [t.name for t in node_tools]

        print(f"[LLM][{node_name}] SYSTEM_PROMPT({prompt_key}):\n{prompt}", flush=True)
        print(
            f"[LLM][{node_name}] {llm_label()} INPUT(prompt_key={prompt_key}, tools={tool_names}):\n{input_text}",
            flush=True,
        )

        result = await agent.ainvoke(
            {"messages": [HumanMessage(content=input_text)]},
            config={"recursion_limit": 50},
        )
        messages = result.get("messages") or []

        audit = _extract_tool_audit(messages)
        out_obj, out_text = _extract_llm_json(messages)

        print(f"[LLM][{node_name}] {llm_label()} OUTPUT:\n{out_text}", flush=True)
        if audit:
            print(
                f"[LLM][{node_name}] TOOLS_USED: {json.dumps(audit, ensure_ascii=False, indent=2, default=str)}",
                flush=True,
            )

        if out_obj is None:
            repaired = await _repair_output_to_json(node_name=node_name, prompt_key=prompt_key, bad_text=out_text)
            if repaired is None:
                return {**state, "error": f"{node_name} did not output parsable JSON", "step": node_name}
            out_obj = repaired

        merged_audit = list(state.get("mcp_audit") or []) + audit
        notifications = _merge_notifications(state, audit)

        patch: Dict[str, Any] = dict(out_obj)
        patch.setdefault("step", node_name)
        patch.setdefault("scenario", scenario)
        patch.setdefault("flow_id", flow_id)

        return {
            **state,
            **patch,
            "mcp_audit": merged_audit,
            "notifications": notifications,
            "step": node_name,
        }

    # -------------------------
    # Node 1: AlarmIngest
    # -------------------------
    # Detect whether there is an alarm and send an email via MCP tool send_email if an alarm is found.
    async def alarm_ingest(state: GraphState) -> GraphState:
        if state.get("error"):
            return {**state, "step": "AlarmIngest"}
        return await _run_agent_node(
            node_name="AlarmIngest",
            prompt_key="alarm_ingest_system",
            state=state,
            node_tools=_pick(read_tool_name, email_tool_name),
        )

    # -------------------------
    # Node 2: ConfirmAlarm
    # -------------------------
    # Re-read Neo4j Flow+SLA, confirm whether it is truly VIOLATED, and set should_remediate.
    async def confirm_alarm(state: GraphState) -> GraphState:
        if state.get("error"):
            return {**state, "step": "ConfirmAlarm"}
        return await _run_agent_node(
            node_name="ConfirmAlarm",
            prompt_key="confirm_alarm_system",
            state=state,
            node_tools=_pick(read_tool_name),
        )

    # -------------------------
    # Node 3: AnalyzePressure
    # -------------------------
    # Analyze bottlenecks via Neo4j topology/link load and find available alternative paths.

    async def analyze_pressure(state: GraphState) -> GraphState:
        if state.get("error") or not state.get("should_remediate", True):
            return {**state, "step": "AnalyzePressure"}
        return await _run_agent_node(
            node_name="AnalyzePressure",
            prompt_key="analyze_pressure_system",
            state=state,
            node_tools=_pick(read_tool_name),
        )

    # -------------------------
    # Node 4: PlanChange
    # -------------------------
    # LLM generates the plan based on analysis (including updates / cli_config / reason).

    async def plan_change(state: GraphState) -> GraphState:
        if state.get("error") or not state.get("should_remediate", True):
            return {**state, "step": "PlanChange"}
        result = await _run_agent_node(
            node_name="PlanChange",
            prompt_key="plan_change_system",
            state=state,
            node_tools=[],  # Pure LLM planning (no MCP tools)
        )
        plan = result.get("plan")
        if not isinstance(plan, dict) or plan.get("plan_ok") is not True:
            return {
                **result,
                "should_remediate": False,
                "error": result.get("error") or "PlanChange did not produce an executable plan",
            }
        return {**result, "should_remediate": True}

    # -------------------------
    # Node 5: ExecuteChange (A2A)
    # -------------------------
    # LLM calls a2a_send_executor_message to send the plan to the executor and organize the result.
    async def execute_change(state: GraphState) -> GraphState:
        if state.get("error") or not state.get("should_remediate", True):
            return {**state, "step": "ExecuteChange"}
        result = await _run_agent_node(
            node_name="ExecuteChange",
            prompt_key="execute_change_system",
            state=state,
            node_tools=_pick("a2a_send_executor_message"),
        )
        audit = result.get("mcp_audit") or []
        executor_calls = [
            item for item in audit if isinstance(item, dict) and item.get("name") == "a2a_send_executor_message"
        ]
        if len(executor_calls) != 1:
            return {
                **result,
                "execution": {
                    "status": "Failure",
                    "log": f"Expected exactly one A2A executor call; observed {len(executor_calls)}",
                },
                "should_remediate": False,
                "error": "ExecuteChange did not make exactly one executor call",
            }

        raw_executor_result = executor_calls[0].get("result")
        executor_result = try_parse_json_object(raw_executor_result) if isinstance(raw_executor_result, str) else None
        status = executor_result.get("status") if isinstance(executor_result, dict) else None
        log = executor_result.get("log") if isinstance(executor_result, dict) else None
        if status not in {"Success", "Failure", "Rollback"} or not isinstance(log, str):
            return {
                **result,
                "execution": {"status": "Failure", "log": f"Invalid executor response: {raw_executor_result}"},
                "should_remediate": False,
                "error": "Executor returned an invalid response",
            }

        execution = {"status": status, "log": log}
        if status != "Success":
            return {
                **result,
                "execution": execution,
                "should_remediate": False,
                "error": f"Executor returned {status}",
            }
        return {**result, "execution": execution, "should_remediate": True}

    # -------------------------
    # Node 6: RegressionVerify
    # -------------------------
    # LLM uses write_neo4j_cypher to write back link load + Flow(rate/latency/status) and outputs verification.
    async def regression_verify(state: GraphState) -> GraphState:
        if state.get("error") or not state.get("should_remediate", True):
            return {**state, "step": "RegressionVerify"}
        return await _run_agent_node(
            node_name="RegressionVerify",
            prompt_key="regression_verify_system",
            state=state,
            node_tools=_pick(read_tool_name, write_tool_name),
        )

    g = StateGraph(GraphState)
    g.add_node("AlarmIngest", alarm_ingest)
    g.add_node("ConfirmAlarm", confirm_alarm)
    g.add_node("AnalyzePressure", analyze_pressure)
    g.add_node("PlanChange", plan_change)
    g.add_node("ExecuteChange", execute_change)
    g.add_node("RegressionVerify", regression_verify)

    g.set_entry_point("AlarmIngest")
    g.add_edge("AlarmIngest", "ConfirmAlarm")

    # ConfirmAlarm may early-stop
    def _route_after_confirm(state: GraphState) -> str:
        return END if not state.get("should_remediate", True) else "AnalyzePressure"

    g.add_conditional_edges("ConfirmAlarm", _route_after_confirm, {"AnalyzePressure": "AnalyzePressure", END: END})

    # AnalyzePressure may also early-stop due to no alternative path
    def _route_after_analyze(state: GraphState) -> str:
        return END if not state.get("should_remediate", True) else "PlanChange"

    g.add_conditional_edges("AnalyzePressure", _route_after_analyze, {"PlanChange": "PlanChange", END: END})

    def _route_after_plan(state: GraphState) -> str:
        return END if not state.get("should_remediate", True) else "ExecuteChange"

    g.add_conditional_edges("PlanChange", _route_after_plan, {"ExecuteChange": "ExecuteChange", END: END})

    def _route_after_execute(state: GraphState) -> str:
        return END if not state.get("should_remediate", True) else "RegressionVerify"

    g.add_conditional_edges(
        "ExecuteChange",
        _route_after_execute,
        {"RegressionVerify": "RegressionVerify", END: END},
    )
    g.add_edge("RegressionVerify", END)

    return g.compile()
